eureka:
  client:
    fetch-registry: true
    instance:
      hostname: localhost
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
microservices:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment     
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder       
